name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          yarn

      - name: build-all
        run: |
          yarn build:all

      # - name: Publish
      #   run: |
      #     npm publish